### ISSUE TITLE
ask_question does not support Fixnum defaults

### ISSUE THREAD

**Issue by JonathanSerafini** [spox/bogo-ui#1]
If you have a SparkleFormation parameter where the default is a Fixnum ( ex.: default 60 ), ask_question will die with ERROR: NoMethodError: undefined method `empty?' for 60:Fixnum

**Comment by chrisroberts** [comment]
This fix has been applied and released. Thanks so much for reporting it!

**Comment by JonathanSerafini** [comment]
Awesome, thanks Chris
