### ISSUE TITLE
[bug] fixnum not processed correctly

### ISSUE THREAD

**Issue by baptiste-ls** [spox/bogo-ui#4]
`question = App Scaling Cooldown
opts = {"default"=>60, "hide_default"=>false, "no_echo"=>false}
default = 60
ERROR: NoMethodError: undefined method `empty?' for 60:Fixnum`

I found that in ui.rb `default_string = !default.empty? && opts[:hide_default] ? '*****' : default` by adding trace manually.

tried with ruby 2.3 and 2.1.

**Comment by slyness** [comment]
/me raises hand

Got it too.

**Comment by baptiste-ls** [comment]
👍
